### ISSUE TITLE
部分浏览器无法正常显示QQ头像

### ISSUE THREAD

**Issue by iqiqiya** [Zisbusy/Akina-for-Typecho#1]
### 问题如下图所示：
使用Chrome与Firefox测试结果
![360截图20191127111323464](https://user-images.githubusercontent.com/43666095/69690494-f8363700-1106-11ea-84bb-662255a00b50.jpg)
### 我这里想了两个办法
第一可以使用https://qlogo1.store.qq.com/qzone/QQ号/QQ号/100这个接口
但缺点是只有100与640大小
第二可以将`$headimg = "http://q1.qlogo.cn/g?b=".$type."&nk=".$QQ."&s=".$size."";`进行封装，
先保存至本地转为内链
### 希望可以优化
我改的代码
[https://github.com/iqiqiya/iqiqiya-API/blob/master/QQ/index.php](https://github.com/iqiqiya/iqiqiya-API/blob/master/QQ/index.php)

**Comment by Zisbusy** [comment]
已经优化了头像这方面的逻辑
