### ISSUE TITLE
[问题反馈]关于文章目录的问题

### ISSUE THREAD

**Issue by Youwenqwq** [Zisbusy/Akina-for-Typecho#10]
在尝鲜了Beta版本以后，各方面体验还算不错，目前发现文章目录有点小问题，具体如下

1.当文章目录过长时，超出的部分始终会在页面外而无法显示
2.文章目录过长时，页面可以无限向下拖动

[演示视频](https://dl.welain.com/img/videos/%E4%B8%AA%E4%BA%BA%20ShareList%20%E7%AE%80%E5%8D%95%E7%BE%8E%E5%8C%96%E6%95%99%E7%A8%8B%20-%20Youwen%20%E5%92%8C%E5%8F%A6%E5%A4%96%204%20%E4%B8%AA%E9%A1%B5%E9%9D%A2%20-%20%E4%B8%AA%E4%BA%BA%20-%20Microsoft%E2%80%8B%20Edge%202021-08-31%2015-36-05.mp4?preview)

3.这个应该不算个Bug，就是H4和H5标签也会显示在目录里，如果在H4与H5标签上放上一些注意事项，会显得目录有点别扭，但是看起来咋改都不太妥的亚子

**Comment by Zisbusy** [comment]
你标题题太太太多了，我尽量优化一下吧。

**Comment by Zisbusy** [comment]
问题三，可以修改 functions.php 第 320 行 为     $obj = preg_replace_callback('/<h([1-3])(.*?)>(.*?)<\/h\1>/i', function($obj) {

**Comment by Youwenqwq** [comment]
> 你标题题太太太多了，我尽量优化一下吧。

好的，谢谢

**Comment by Youwenqwq** [comment]
> 你标题题太太太多了，我尽量优化一下吧。

![image](https://user-images.githubusercontent.com/25259258/131468039-69ca55da-b3c0-4824-afc9-2490fadaa169.png)

去掉H4和H5以后没1，2两个bug了（因为不那么长了），像我写这种标题巨多的人应该不太多😂

如果过长的话，个人认为可以为超出的标题加上向下滑动显示，这样就可以固定文章目录那个小方框的长度了，也比较方便
