### ISSUE TITLE
1.2Typecho版本适配

### ISSUE THREAD

**Issue by banjuer** [Zisbusy/Akina-for-Typecho#15]
启用主题后进入首页会报错
![image](https://user-images.githubusercontent.com/18739609/161253586-8cb3928f-18dd-4aee-99bd-28a4275436d7.png)

**Comment by Zisbusy** [comment]
近期已经在测试新版本的兼容性。

**Comment by banjuer** [comment]
> 近期已经在测试新版本的兼容性。

忘记说了, 我用的是postgresql

**Comment by Zisbusy** [comment]
postgresql 没有计划兼容。
