### ISSUE TITLE
进入文章会报错，post.php 41行 $bgImgUrl  未定义 

### ISSUE THREAD

**Issue by lovewrong** [Zisbusy/Akina-for-Typecho#17]
把 $bgImgUrl 定义在if 外面就好了

**Comment by lovewrong** [comment]
Warning: Undefined variable $bgImgUrl in /www/wwwroot/onmoe.com/usr/themes/Akina/page.php on line 34  关于页面 也是

**Comment by Zisbusy** [comment]
你PHP版本是多少？

**Comment by lovewrong** [comment]
7.4 用宝塔面板装的

**Comment by lovewrong** [comment]
> PHP版本是多少？

记错了.. 刚看了一下 是8.0

**Comment by Zisbusy** [comment]
> > PHP版本是多少？
> 
> 记错了.. 刚看了一下 是8.0

我说我怎么复现不出来

**Comment by Zisbusy** [comment]
已经修复
