### ISSUE TITLE
iconfont图标无法加载

### ISSUE THREAD

**Issue by Jay-Codeman** [Zisbusy/Akina-for-Typecho#18]
如果使用ip地址进行访问，iconfont图标可以显示；
但如果使用域名进行访问，所有iconfont图标都变成方块了。

**Comment by Zisbusy** [comment]
跨域问题，结合自己的环境，搜索解决。

**Comment by Jay-Codeman** [comment]
已解决，是跨域问题，非常感谢作者!
把自己的情况和解决方法说一下：
**问题：**用ip地址访问博客，一切正常。用域名访问，iconfont出现方块字（如右上角的搜索等图标）。F12控制台抛异常：......has been blocked by CORS policy: No ‘Access-Control-Allow-Origin‘ .........
原因的确是作者说的跨域问题，域名和对应的IP之间请求是跨域的一种情况。

**解决方案：**使用Nginx反向代理解决。在Nginx安装目录下的`conf/nginx.conf`文件中增加一个server，内容如下：
```
server
	{
    	listen 80;                         //填写需要监听的端口
        server_name xxxx.com;   //填写需要配置访问主页的域名，对我来说也就是出现问题的那个域名
        
        location / {
        	proxy_pass http://xxx.xxx.xxx.xxx;   //代理到其他server的接口
   		
                //ladd_header表示 Nginx 会在 response 中添加一些额外的响应头信息给客户端。
                add_header Access-Control-Allow-Origin * always;
    		add_header Access-Control-Allow-Headers *;
    		add_header Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS";
        }
    }
```
    }
