### ISSUE TITLE
更新4.1.3后，聚焦模块显示异常

### ISSUE THREAD

**Issue by realzsy** [Zisbusy/Akina-for-Typecho#19]
RT
更新最新的4.1.3版本后，聚焦板块的第三张图会跳行，之前4.0是显示正常的。
https://cdn.zsy.life/zpic/220614/4ffd3a8a6eef0.jpg

博客地址：https://blog.zsy.life

**Comment by Zisbusy** [comment]
问题未复现，博客显示正常。

**Comment by Zisbusy** [comment]
问题未复现，博客显示正常。
