### ISSUE TITLE
关于友链、留言部分无法显示的问题

### ISSUE THREAD

**Issue by RubiscoQAQ** [Zisbusy/Akina-for-Typecho#2]
是不是伪静态没有配好造成的？
不新建页面就404，新建独立页面就是空白页面

**Comment by Zisbusy** [comment]
配置伪静态后，新建独立页面选择对应模板，空白是因为你没有填写内容。

**Comment by RubiscoQAQ** [comment]
> 配置伪静态后，新建独立页面选择对应模板，空白是因为你没有填写内容。

模板没有links的选项出现。只有归档和page两个选项![image](https://user-images.githubusercontent.com/65221124/83840489-49b42400-a731-11ea-8918-63a7a405fe46.jpeg)

**Comment by RubiscoQAQ** [comment]
抱歉，是我的问题。不小心改了包名。主题做的超棒！超级感谢！
