### ISSUE TITLE
希望文章有目录

### ISSUE THREAD

**Issue by ql-isaac** [Zisbusy/Akina-for-Typecho#4]
![image](https://user-images.githubusercontent.com/53886119/110238356-2e09d280-7f7c-11eb-89c8-18ad58b8cc0a.png)
像这样

**Comment by Zisbusy** [comment]
我尽量

**Comment by Youwenqwq** [comment]
这是个好东西，加油做(๑•̀ㅂ•́)و✧

**Comment by Zisbusy** [comment]
已经增加，
