### ISSUE TITLE
[功能请求]希望可以增加选项为头图增加蒙版

### ISSUE THREAD

**Issue by Youwenqwq** [Zisbusy/Akina-for-Typecho#5]
如题，希望可以在主题设置里为首页头图设置一个蒙版，造成灰蒙蒙的效果，和最开始的图片更加贴切（直接用一张图片可能会有点突兀
![屏幕截图 2021-03-20 015348.png](https://i.loli.net/2021/03/20/bsLzpCoWYncJmMI.png)

**Comment by Zisbusy** [comment]
在style.css中添加以下样式让给背景一个带有颜色的蒙版，可以调整background-color的值去修改这个颜色。
#centerbg::before {
    content: "";
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    z-index: 0;
    background-color: rgb(177 177 177 / 25%);
}
或者添加下面的样式来让背景有一个模糊的效果，
#centerbg::before {
    content: "";
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    background: inherit;
    filter: blur(2px);
    z-index: 0;
}

**Comment by Youwenqwq** [comment]
> 在style.css中添加以下样式让给背景一个带有颜色的蒙版，可以调整background-color的值去修改这个颜色。
> #centerbg::before {
> content: "";
> position: absolute;
> top: 0;
> bottom: 0;
> left: 0;
> right: 0;
> z-index: 0;
> background-color: rgb(177 177 177 / 25%);
> }
> 或者添加下面的样式来让背景有一个模糊的效果，
> #centerbg::before {
> content: "";
> position: absolute;
> top: 0;
> bottom: 0;
> left: 0;
> right: 0;
> background: inherit;
> filter: blur(2px);
> z-index: 0;
> }

已修改，感谢作者(●'◡'●)
