### ISSUE TITLE
【Bug】首页聚焦文章设置后报错 Call to undefined function img_postthumb()

### ISSUE THREAD

**Issue by Tacks9** [Zisbusy/Akina-for-Typecho#7]
## Bug 首页聚焦文章设置后报错 Call to undefined function img_postthumb()

- 时间： `Fri Jul 30 10:52:55 CST 2021`
- 发现者：`Tacks`

### BUG 信息

- BUG 描述： 
       目前看到Akina作者有进行新的提交。关于{ [删除获取文章第一张图片代码](https://github.com/Zisbusy/Akina-for-Typecho/commit/c15d97d94145976d1fc17ea6784e5d7cd3883b57) } 这次提交，将`img_postthumb()` 函数移除，但是在主页代码 { [Index.php](https://github.com/Zisbusy/Akina-for-Typecho/blob/master/Akina/index.php) } 中，仍然有`img_postthumb()`函数的调用。导致在设置 “首页聚焦文章” 的时候，如果后台设置的文章是自动获取图片，那么首页会进行报错`Call to undefined function img_postthumb()` 函数未定义。 

- BUG截图：
 
**【后台设置聚焦文章】**
 ![image](https://user-images.githubusercontent.com/46589852/127592548-5c1e6062-c83f-48ba-a8d2-df9a55e6d60a.png)
**【前台首页打开报错】**
![image](https://user-images.githubusercontent.com/46589852/127592611-be39e50f-1f35-490e-a468-249231a513ee.png)

**Comment by Zisbusy** [comment]
这里的逻辑还要再改改，感谢提醒。

**Comment by Tacks9** [comment]
> 这里的逻辑还要再改改，感谢提醒。

还有个问题，如果后期升级的话，我们是直接Akina代码源文件替换即可吗！

**Comment by Zisbusy** [comment]
牵扯到一些设置项目，建议替换后重新启用一下，（会导致主题配置丢失，注意备份）

**Comment by Zisbusy** [comment]
已经删除调用代码，感谢反馈。
