### ISSUE TITLE
【Hope】希望表格可以支持更好一些

### ISSUE THREAD

**Issue by Tacks9** [Zisbusy/Akina-for-Typecho#8]
- 目前使用原生的md语法编写的表格形式，在web端看起来还行，在手机上不能看全部的内容，屏幕也不能缩小，会比较影响使用
- 不知道表格的绘制，作者有什么好的意见？

**Comment by Zisbusy** [comment]
能否截图上传，我具体看一下。

**Comment by Zisbusy** [comment]
![image](https://user-images.githubusercontent.com/49525016/129166080-4a289106-3406-4e07-813d-3c872e23c854.png)
问题已经修复，请下载覆盖后刷新浏览器缓存。

**Comment by Tacks9** [comment]
好滴感谢！

**Comment by Tacks9** [comment]
- 您好，有个js报错
```
global.js:436 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at global.js:436
```

![image](https://user-images.githubusercontent.com/46589852/129323800-1f5b0ba2-6681-4550-813e-77d5741648a4.png)
![image](https://user-images.githubusercontent.com/46589852/129323815-f1f75f88-d630-41c9-bc2a-1997ed24f7ba.png)

**Comment by Zisbusy** [comment]
我这边额浏览器似乎没有报错，我再看看。

**Comment by Zisbusy** [comment]
刚看见问题，一个数为了测试写死了，忘记改了。稍后修复。

**Comment by Tacks9** [comment]
代码中
```js
let tables = document.getElementsByTagName("table");
if (tables.length != 0) {
        for ( i = 0; i < 2; i++ ) { ///  这个地方 i不应该是2呀
``` 

https://github.com/Zisbusy/Akina-for-Typecho/commit/456bad59030a66ea1043f533e6181b5caba3754b#r54833781

**Comment by Zisbusy** [comment]
应该是tables.length。

**Comment by Tacks9** [comment]
![image](https://user-images.githubusercontent.com/46589852/129325512-8f4ac23e-508e-4307-91c6-5f4d510dcbfc.png)


- 感谢，问题已修复！

**Comment by Tacks9** [comment]
![image](https://user-images.githubusercontent.com/46589852/129326305-eeea53e9-9b39-435b-97e5-92aedc05c59e.png)
