### ISSUE TITLE
【Akina For Typecho 版本迭代】相关问题

### ISSUE THREAD

**Issue by Tacks9** [Zisbusy/Akina-for-Typecho#9]
[Akina For Typecho 版本迭代](https://docs.qq.com/sheet/DUFVrV3h2b25vWHhQ?tab=BB08J2)

[releases版本](https://github.com/Zisbusy/Akina-for-Typecho/releases)

- 看大佬已经基本功能都完成了！很奈斯啊，打算什么时候发布一版稳定版！貌似最新的是 `v3.4.5`

**Comment by Zisbusy** [comment]
还有两个功能，估计到8月底发布版本。
